export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const GAME_OVER = 'GAME_OVER';
